apiVersion: "bitnami.com/v1alpha1"
kind: "SealedSecret"
metadata:
  annotations: {}
  name: "azure-pg-user"
  namespace: "cdtn-admin"
spec:
  encryptedData:
  template:
    metadata:
      annotations: {}
      name: "azure-pg-user"
    type: "Opaque"
