extends:
  - "@socialgouv/eslint-config-recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/all"
  - "plugin:import/typescript"
  - "prettier/@typescript-eslint"
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
plugins:
  - '@typescript-eslint'
root: true
rules:
  "@typescript-eslint/no-type-alias": off
  "@typescript-eslint/prefer-readonly-parameter-types": off
  "@typescript-eslint/typedef": off
  import/no-unresolved:
    - error
    - ignore:
      - "^@socialgouv/kosko-charts/"

  import/order:
    - error
    - alphabetize:
        caseInsensitive: true
        order: asc
      newlines-between: always
      pathGroups:
        - pattern: "@socialgouv/kosko-charts/**"
          group: external
          position: after
      pathGroupsExcludedImportTypes:
        - builtin

overrides:
  - files: jest.config.js
    rules:
      "@typescript-eslint/no-var-requires": off
