extends:
  - "@socialgouv/eslint-config-recommended"
  - "plugin:import/typescript"
  - "plugin:@typescript-eslint/recommended"
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
root: true
rules:
  "@typescript-eslint/no-use-before-define": off
  "@typescript-eslint/prefer-reduce-type-parameter": off

  import/no-unresolved: off
  import/order:
    - error
    - groups:
        - internal
        - builtin
        - external
        - parent
        - sibling
        - index
      newlines-between: ignore
      pathGroups:
        - pattern: "@socialgouv/kosko-charts/**"
          group: index

overrides:
  - files: jest.config.js
    rules:
      "@typescript-eslint/no-var-requires": off
