name: Boto

on:
  - issue_comment

jobs:
  Act:
    if: ${{ github.event.issue.pull_request }}

    runs-on: ubuntu-latest

    outputs:
      BOOL_TRIGGERED: ${{ steps.prcomm.outputs.BOOL_TRIGGERED }}
      TRAILING_TOKEN : ${{ steps.prcomm.outputs.TRAILING_TOKEN  }}
      TRAILING_LINE : ${{ steps.prcomm.outputs.TRAILING_LINE  }}
      RUN_URL : ${{ steps.vars.outputs.run-url  }}

    steps:
      - name: Listen for PR Comments
        id: prcomm
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "@SocialGroovyBot"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
      
      - run: |
           echo "BOOL_TRIGGERED : ${{ steps.prcomm.outputs.BOOL_TRIGGERED }}"
           echo "TRAILING_TOKEN : ${{ steps.prcomm.outputs.TRAILING_TOKEN }}"
           echo "TRAILING_LINE : ${{ steps.prcomm.outputs.TRAILING_LINE }}"
           echo "RUN_URL : ${{ steps.vars.outputs.run-url }}"
           echo "github.event.comment.id : ${{ github.event.comment.id }}"
           echo "github.event.issue.number : ${{ github.event.issue.number }}"

      - name: Add reaction
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'True'
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ github.event.comment.id }}
          comment-author: 'SocialGroovyBot'
          reaction-type: eyes

      - name: Create comment
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'True'
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-author: 'SocialGroovyBot'
          body: |
            [Running `${{ steps.vars.outputs.TRAILING_LINE }}`][1]
            [1]: ${{ steps.vars.outputs.run-url }}

  Yarn:
    needs:
      - Act

    if: |
      (
        needs.Act.outputs.BOOL_TRIGGERED == 'True'
        &&
        needs.Act.outputs.TRAILING_TOKEN == 'yarn'
      )

    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 14.x
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.x

      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: init
        shell: bash
        run: |
          echo "::set-output name=yarn_cache::$(yarn cache dir)"
          #
          echo "Node $(node --version)"
          echo "NPM $(npm --version)"
          echo "Npx $(npx --version)"
          echo "Yarn $(yarn --version)"
          
      - name: Cache Yarn packages
        id: yarn_cache_packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.init.outputs.yarn_cache }}
          key: ${{ runner.os }}-yarn_cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn_cache-
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Installing
        run: yarn --frozen-lockfile --perfer-offline --link-duplicates

      - name: Run
        run: |
          ${{ needs.Act.outputs.TRAILING_LINE }}

      - uses: EndBug/add-and-commit@v5
        env:
          HUSKY_SKIP_HOOKS: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          author_email: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          message: "chore(:robot:): ${{ needs.Act.outputs.TRAILING_LINE }}"
